# Generated by Django 2.2 on 2020-09-12 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('title', 'user')},
        ),
    ]
