# Generated by Django 2.2 on 2020-09-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_hashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
